version: '2'

services:
  backend:
    build: 'docker/backend'
    links:
      - memcached
      - mongo
    volumes:
      - './app/:/var/www/hawk-api/app:ro'
      - './bin/:/var/www/hawk-api/bin:ro'
      - './public/:/var/www/hawk-api/public:ro'
      - './src/:/var/www/hawk-api/src:ro'
      - './vendor:/var/www/hawk-api/vendor:ro'
      - './composer.json:/var/www/hawk-api/composer.json:ro'
      - './phpunit.xml:/var/www/hawk-api/phpunit.xml:ro'
      - './.env/:/var/www/hawk-api/.env:ro'
      - './.php_cs:/var/www/hawk-api/.php_cs:ro'
    working_dir: '/var/www/hawk-api'
  nginx:
    image: 'nginx:latest'
    ports:
      - 8080:8080
    links:
      - backend
    volumes:
      - './docker/nginx/hawk-api.conf:/etc/nginx/conf.d/hawk-api.conf'
    volumes_from:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  memcached:
    image: 'memcached:alpine'
