<?php

declare(strict_types=1);

namespace App\Components\Models;

class Team extends BaseModel
{
    protected const COLLECTION_NAME = 'team:';

    /**
     * Membership's unique identifier
     *
     * @var string|null
     */
    public $_id;

    /**
     * User's id which take part
     *
     * @var string|null
     */
    public $userId;

    /**
     * Role type
     *
     * @var string|null
     */
    public $role;

    /**
     * Pending status
     *
     * @var bool|null
     */
    public $isPending;

    /**
     * Project._id at collection name, that team belongs to
     *
     * @var string
     */
    public $projectId;

    /**
     * Team constructor.
     *
     * @param string $projectId Associated project identifier
     * @param array  $args      Values as assoc array to fill model
     */
    public function __construct(string $projectId, array $args = [])
    {
        $this->projectId = $projectId;
        parent::__construct($args);
    }

    public function all(array $filter = []): array
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * Return collection name
     *
     * @return string
     */
    public function collectionName(): string
    {
        return self::COLLECTION_NAME . $this->projectId;
    }
}
